export const ADD_ACCOUNT_DATA = 'ADD_ACCOUNT_DATA'
export const ACCOUNT_DATA_LOADING = 'ACCOUNT_DATA_LOADING'
export const ACCOUNT_DATA_FAILED = 'ACCOUNT_DATA_FAILED'
export const SET_SETTING_FORM_DATA = 'SET_SETTING_FORM_DATA'